/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AssetDeleteResponseDto,
  AssetDetailResponseDto,
  AssetUploadResponseDto,
  AssetsControllerUploadPublicParams,
  UploadFileRequestDto,
} from '../app.schemas';

import service from '../../../services/index';

export const assetsControllerGetDetail = (id: string, signal?: AbortSignal) => {
  return service<AssetDetailResponseDto>({ url: `/assets/${id}`, method: 'GET', signal });
};

export const getAssetsControllerGetDetailQueryKey = (id?: string) => {
  return [`/assets/${id}`] as const;
};

export const getAssetsControllerGetDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof assetsControllerGetDetail>>,
  TError = unknown,
>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsControllerGetDetail>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAssetsControllerGetDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof assetsControllerGetDetail>>> = ({ signal }) =>
    assetsControllerGetDetail(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof assetsControllerGetDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AssetsControllerGetDetailQueryResult = NonNullable<Awaited<ReturnType<typeof assetsControllerGetDetail>>>;
export type AssetsControllerGetDetailQueryError = unknown;

export function useAssetsControllerGetDetail<
  TData = Awaited<ReturnType<typeof assetsControllerGetDetail>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsControllerGetDetail>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetsControllerGetDetail>>,
          TError,
          Awaited<ReturnType<typeof assetsControllerGetDetail>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAssetsControllerGetDetail<
  TData = Awaited<ReturnType<typeof assetsControllerGetDetail>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsControllerGetDetail>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetsControllerGetDetail>>,
          TError,
          Awaited<ReturnType<typeof assetsControllerGetDetail>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAssetsControllerGetDetail<
  TData = Awaited<ReturnType<typeof assetsControllerGetDetail>>,
  TError = unknown,
>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsControllerGetDetail>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAssetsControllerGetDetail<
  TData = Awaited<ReturnType<typeof assetsControllerGetDetail>>,
  TError = unknown,
>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assetsControllerGetDetail>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAssetsControllerGetDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const assetsControllerDelete = (id: string) => {
  return service<AssetDeleteResponseDto>({ url: `/assets/${id}`, method: 'DELETE' });
};

export const getAssetsControllerDeleteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof assetsControllerDelete>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof assetsControllerDelete>>, TError, { id: string }, TContext> => {
  const mutationKey = ['assetsControllerDelete'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof assetsControllerDelete>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return assetsControllerDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssetsControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof assetsControllerDelete>>>;

export type AssetsControllerDeleteMutationError = unknown;

export const useAssetsControllerDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof assetsControllerDelete>>, TError, { id: string }, TContext>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof assetsControllerDelete>>, TError, { id: string }, TContext> => {
  const mutationOptions = getAssetsControllerDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const assetsControllerUploadPublic = (
  uploadFileRequestDto: UploadFileRequestDto,
  params: AssetsControllerUploadPublicParams,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, uploadFileRequestDto.file);

  return service<AssetUploadResponseDto>({
    url: `/assets/public`,
    method: 'POST',
    headers: { 'Content-Type': 'multipart/form-data' },
    data: formData,
    params,
    signal,
  });
};

export const getAssetsControllerUploadPublicMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetsControllerUploadPublic>>,
    TError,
    { data: UploadFileRequestDto; params: AssetsControllerUploadPublicParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assetsControllerUploadPublic>>,
  TError,
  { data: UploadFileRequestDto; params: AssetsControllerUploadPublicParams },
  TContext
> => {
  const mutationKey = ['assetsControllerUploadPublic'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assetsControllerUploadPublic>>,
    { data: UploadFileRequestDto; params: AssetsControllerUploadPublicParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return assetsControllerUploadPublic(data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssetsControllerUploadPublicMutationResult = NonNullable<
  Awaited<ReturnType<typeof assetsControllerUploadPublic>>
>;
export type AssetsControllerUploadPublicMutationBody = UploadFileRequestDto;
export type AssetsControllerUploadPublicMutationError = unknown;

export const useAssetsControllerUploadPublic = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof assetsControllerUploadPublic>>,
      TError,
      { data: UploadFileRequestDto; params: AssetsControllerUploadPublicParams },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof assetsControllerUploadPublic>>,
  TError,
  { data: UploadFileRequestDto; params: AssetsControllerUploadPublicParams },
  TContext
> => {
  const mutationOptions = getAssetsControllerUploadPublicMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
