export const routes = {
  dashboard: '/dashboard',
  mock: {
    listing: '/mock',
    create: '/mock/create',
    edit: (id: string) => `/mock/edit/${id}`,
    detail: (id: string) => `/mock/${id}`,
  },
  category: {
    listing: '/category',
    create: '/category/create',
    edit: (id: string) => `/category/edit/${id}`,
    detail: (id: string) => `/category/${id}`,
  },
  card: {
    listing: '/card',
    create: '/card/create',
    edit: (id: string) => `/card/edit/${id}`,
    detail: (id: string) => `/card/${id}`,
  },
  product: {
    listing: '/product',
    create: '/product/create',
    edit: (id: string) => `/product/edit/${id}`,
    detail: (id: string) => `/product/${id}`,
  },
  productApproval: {
    listing: '/product-approval',
    create: '/product-approval/create',
    edit: (id: string) => `/product-approval/edit/${id}`,
    detail: (id: string) => `/product-approval/${id}`,
  },
  brand: {
    listing: '/brand',
    create: '/brand/create',
    edit: (id: string) => `/brand/edit/${id}`,
    detail: (id: string) => `/brand/${id}`,
  },
  order: {
    listing: '/order',
    create: '/order/create',
    edit: (id: string) => `/order/edit/${id}`,
    detail: (id: string) => `/order/${id}`,
  },
  supplier: {
    listing: '/supplier',
    create: '/supplier/create',
    edit: (id: string) => `/supplier/edit/${id}`,
    detail: (id: string) => `/supplier/${id}`,
  },
  user: {
    listing: '/user',
    create: '/user/create',
    edit: (id: string) => `/user/edit/${id}`,
    detail: (id: string) => `/user/${id}`,
  },
  admin: {
    listing: '/admin',
    create: '/admin/create',
    edit: (id: string) => `/admin/edit/${id}`,
    detail: (id: string) => `/admin/${id}`,
  },
  role: {
    listing: '/role',
    create: '/role/create',
    edit: (id: string) => `/role/edit/${id}`,
    detail: (id: string) => `/role/${id}`,
  },
  permission: {
    listing: '/permission',
    create: '/permission/create',
    edit: (id: string) => `/permission/edit/${id}`,
    detail: (id: string) => `/permission/${id}`,
  },
  report: {
    listing: '/report',
    create: '/report/create',
    edit: (id: string) => `/report/edit/${id}`,
    detail: (id: string) => `/report/${id}`,
  },
  auth: {
    signIn: '/auth/sign-in',
    signUp: '/auth/sign-up',
    resetPassword: '/auth/reset-password',
    createPassword: '/auth/create-password',
    forgotPassword: '/auth/forgot-password',
    changePassword: '/auth/change-password',
  },
};
