/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ActionResponseDto,
  BranchControllerFindAllParams,
  BranchControllerFindOneParams,
  CreateBranchDto,
  CreateBranchResponseDto,
  DetailBranchesResponseDto,
  ListBranchesResponseDto,
  UpdateBranchDto,
  UpdateBranchResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const branchControllerCreate = (createBranchDto: CreateBranchDto, signal?: AbortSignal) => {
  return service<CreateBranchResponseDto>({
    url: `/branch`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createBranchDto,
    signal,
  });
};

export const getBranchControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof branchControllerCreate>>,
    TError,
    { data: CreateBranchDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof branchControllerCreate>>,
  TError,
  { data: CreateBranchDto },
  TContext
> => {
  const mutationKey = ['branchControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof branchControllerCreate>>, { data: CreateBranchDto }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return branchControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type BranchControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof branchControllerCreate>>>;
export type BranchControllerCreateMutationBody = CreateBranchDto;
export type BranchControllerCreateMutationError = unknown;

export const useBranchControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof branchControllerCreate>>,
      TError,
      { data: CreateBranchDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof branchControllerCreate>>,
  TError,
  { data: CreateBranchDto },
  TContext
> => {
  const mutationOptions = getBranchControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const branchControllerFindAll = (params?: BranchControllerFindAllParams, signal?: AbortSignal) => {
  return service<ListBranchesResponseDto>({ url: `/branch`, method: 'GET', params, signal });
};

export const getBranchControllerFindAllQueryKey = (params?: BranchControllerFindAllParams) => {
  return [`/branch`, ...(params ? [params] : [])] as const;
};

export const getBranchControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof branchControllerFindAll>>,
  TError = unknown,
>(
  params?: BranchControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof branchControllerFindAll>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBranchControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof branchControllerFindAll>>> = ({ signal }) =>
    branchControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof branchControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BranchControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof branchControllerFindAll>>>;
export type BranchControllerFindAllQueryError = unknown;

export function useBranchControllerFindAll<
  TData = Awaited<ReturnType<typeof branchControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | BranchControllerFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof branchControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof branchControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof branchControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBranchControllerFindAll<
  TData = Awaited<ReturnType<typeof branchControllerFindAll>>,
  TError = unknown,
>(
  params?: BranchControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof branchControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof branchControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof branchControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBranchControllerFindAll<
  TData = Awaited<ReturnType<typeof branchControllerFindAll>>,
  TError = unknown,
>(
  params?: BranchControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof branchControllerFindAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBranchControllerFindAll<
  TData = Awaited<ReturnType<typeof branchControllerFindAll>>,
  TError = unknown,
>(
  params?: BranchControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof branchControllerFindAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBranchControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const branchControllerFindOne = (id: string, params?: BranchControllerFindOneParams, signal?: AbortSignal) => {
  return service<DetailBranchesResponseDto>({ url: `/branch/${id}`, method: 'GET', params, signal });
};

export const getBranchControllerFindOneQueryKey = (id?: string, params?: BranchControllerFindOneParams) => {
  return [`/branch/${id}`, ...(params ? [params] : [])] as const;
};

export const getBranchControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof branchControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: BranchControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof branchControllerFindOne>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBranchControllerFindOneQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof branchControllerFindOne>>> = ({ signal }) =>
    branchControllerFindOne(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof branchControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BranchControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof branchControllerFindOne>>>;
export type BranchControllerFindOneQueryError = unknown;

export function useBranchControllerFindOne<
  TData = Awaited<ReturnType<typeof branchControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params: undefined | BranchControllerFindOneParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof branchControllerFindOne>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof branchControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof branchControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBranchControllerFindOne<
  TData = Awaited<ReturnType<typeof branchControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: BranchControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof branchControllerFindOne>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof branchControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof branchControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBranchControllerFindOne<
  TData = Awaited<ReturnType<typeof branchControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: BranchControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof branchControllerFindOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBranchControllerFindOne<
  TData = Awaited<ReturnType<typeof branchControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: BranchControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof branchControllerFindOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBranchControllerFindOneQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const branchControllerUpdate = (id: string, updateBranchDto: UpdateBranchDto) => {
  return service<UpdateBranchResponseDto>({
    url: `/branch/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateBranchDto,
  });
};

export const getBranchControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof branchControllerUpdate>>,
    TError,
    { id: string; data: UpdateBranchDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof branchControllerUpdate>>,
  TError,
  { id: string; data: UpdateBranchDto },
  TContext
> => {
  const mutationKey = ['branchControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof branchControllerUpdate>>,
    { id: string; data: UpdateBranchDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return branchControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type BranchControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof branchControllerUpdate>>>;
export type BranchControllerUpdateMutationBody = UpdateBranchDto;
export type BranchControllerUpdateMutationError = unknown;

export const useBranchControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof branchControllerUpdate>>,
      TError,
      { id: string; data: UpdateBranchDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof branchControllerUpdate>>,
  TError,
  { id: string; data: UpdateBranchDto },
  TContext
> => {
  const mutationOptions = getBranchControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const branchControllerRemove = (id: string) => {
  return service<ActionResponseDto>({ url: `/branch/${id}`, method: 'DELETE' });
};

export const getBranchControllerRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof branchControllerRemove>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof branchControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationKey = ['branchControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof branchControllerRemove>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return branchControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type BranchControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof branchControllerRemove>>>;

export type BranchControllerRemoveMutationError = unknown;

export const useBranchControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof branchControllerRemove>>, TError, { id: string }, TContext>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof branchControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationOptions = getBranchControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const branchControllerDeactivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/branch/${id}/deactivate`, method: 'DELETE' });
};

export const getBranchControllerDeactivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof branchControllerDeactivate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof branchControllerDeactivate>>, TError, { id: string }, TContext> => {
  const mutationKey = ['branchControllerDeactivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof branchControllerDeactivate>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return branchControllerDeactivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type BranchControllerDeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof branchControllerDeactivate>>
>;

export type BranchControllerDeactivateMutationError = unknown;

export const useBranchControllerDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof branchControllerDeactivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof branchControllerDeactivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getBranchControllerDeactivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const branchControllerActivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/branch/${id}/activate`, method: 'PATCH' });
};

export const getBranchControllerActivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof branchControllerActivate>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof branchControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationKey = ['branchControllerActivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof branchControllerActivate>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return branchControllerActivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type BranchControllerActivateMutationResult = NonNullable<Awaited<ReturnType<typeof branchControllerActivate>>>;

export type BranchControllerActivateMutationError = unknown;

export const useBranchControllerActivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof branchControllerActivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof branchControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getBranchControllerActivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
