/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ActionResponseDto,
  ClassLevelControllerFindAllParams,
  ClassLevelControllerFindOneParams,
  CreateClassLevelDto,
  CreateClassLevelResponseDto,
  DetailClassLevelsResponseDto,
  ListClassLevelsResponseDto,
  UpdateClassLevelDto,
  UpdateClassLevelResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const classLevelControllerCreate = (createClassLevelDto: CreateClassLevelDto, signal?: AbortSignal) => {
  return service<CreateClassLevelResponseDto>({
    url: `/class-level`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createClassLevelDto,
    signal,
  });
};

export const getClassLevelControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof classLevelControllerCreate>>,
    TError,
    { data: CreateClassLevelDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof classLevelControllerCreate>>,
  TError,
  { data: CreateClassLevelDto },
  TContext
> => {
  const mutationKey = ['classLevelControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof classLevelControllerCreate>>,
    { data: CreateClassLevelDto }
  > = (props) => {
    const { data } = props ?? {};

    return classLevelControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClassLevelControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof classLevelControllerCreate>>
>;
export type ClassLevelControllerCreateMutationBody = CreateClassLevelDto;
export type ClassLevelControllerCreateMutationError = unknown;

export const useClassLevelControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof classLevelControllerCreate>>,
      TError,
      { data: CreateClassLevelDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof classLevelControllerCreate>>,
  TError,
  { data: CreateClassLevelDto },
  TContext
> => {
  const mutationOptions = getClassLevelControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const classLevelControllerFindAll = (params?: ClassLevelControllerFindAllParams, signal?: AbortSignal) => {
  return service<ListClassLevelsResponseDto>({ url: `/class-level`, method: 'GET', params, signal });
};

export const getClassLevelControllerFindAllQueryKey = (params?: ClassLevelControllerFindAllParams) => {
  return [`/class-level`, ...(params ? [params] : [])] as const;
};

export const getClassLevelControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof classLevelControllerFindAll>>,
  TError = unknown,
>(
  params?: ClassLevelControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof classLevelControllerFindAll>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getClassLevelControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof classLevelControllerFindAll>>> = ({ signal }) =>
    classLevelControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof classLevelControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ClassLevelControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof classLevelControllerFindAll>>
>;
export type ClassLevelControllerFindAllQueryError = unknown;

export function useClassLevelControllerFindAll<
  TData = Awaited<ReturnType<typeof classLevelControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | ClassLevelControllerFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof classLevelControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof classLevelControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof classLevelControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useClassLevelControllerFindAll<
  TData = Awaited<ReturnType<typeof classLevelControllerFindAll>>,
  TError = unknown,
>(
  params?: ClassLevelControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof classLevelControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof classLevelControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof classLevelControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useClassLevelControllerFindAll<
  TData = Awaited<ReturnType<typeof classLevelControllerFindAll>>,
  TError = unknown,
>(
  params?: ClassLevelControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof classLevelControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useClassLevelControllerFindAll<
  TData = Awaited<ReturnType<typeof classLevelControllerFindAll>>,
  TError = unknown,
>(
  params?: ClassLevelControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof classLevelControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getClassLevelControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const classLevelControllerFindOne = (
  id: string,
  params?: ClassLevelControllerFindOneParams,
  signal?: AbortSignal,
) => {
  return service<DetailClassLevelsResponseDto>({ url: `/class-level/${id}`, method: 'GET', params, signal });
};

export const getClassLevelControllerFindOneQueryKey = (id?: string, params?: ClassLevelControllerFindOneParams) => {
  return [`/class-level/${id}`, ...(params ? [params] : [])] as const;
};

export const getClassLevelControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof classLevelControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: ClassLevelControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof classLevelControllerFindOne>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getClassLevelControllerFindOneQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof classLevelControllerFindOne>>> = ({ signal }) =>
    classLevelControllerFindOne(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof classLevelControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ClassLevelControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof classLevelControllerFindOne>>
>;
export type ClassLevelControllerFindOneQueryError = unknown;

export function useClassLevelControllerFindOne<
  TData = Awaited<ReturnType<typeof classLevelControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params: undefined | ClassLevelControllerFindOneParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof classLevelControllerFindOne>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof classLevelControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof classLevelControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useClassLevelControllerFindOne<
  TData = Awaited<ReturnType<typeof classLevelControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: ClassLevelControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof classLevelControllerFindOne>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof classLevelControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof classLevelControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useClassLevelControllerFindOne<
  TData = Awaited<ReturnType<typeof classLevelControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: ClassLevelControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof classLevelControllerFindOne>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useClassLevelControllerFindOne<
  TData = Awaited<ReturnType<typeof classLevelControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: ClassLevelControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof classLevelControllerFindOne>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getClassLevelControllerFindOneQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const classLevelControllerUpdate = (id: string, updateClassLevelDto: UpdateClassLevelDto) => {
  return service<UpdateClassLevelResponseDto>({
    url: `/class-level/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateClassLevelDto,
  });
};

export const getClassLevelControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof classLevelControllerUpdate>>,
    TError,
    { id: string; data: UpdateClassLevelDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof classLevelControllerUpdate>>,
  TError,
  { id: string; data: UpdateClassLevelDto },
  TContext
> => {
  const mutationKey = ['classLevelControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof classLevelControllerUpdate>>,
    { id: string; data: UpdateClassLevelDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return classLevelControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClassLevelControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof classLevelControllerUpdate>>
>;
export type ClassLevelControllerUpdateMutationBody = UpdateClassLevelDto;
export type ClassLevelControllerUpdateMutationError = unknown;

export const useClassLevelControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof classLevelControllerUpdate>>,
      TError,
      { id: string; data: UpdateClassLevelDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof classLevelControllerUpdate>>,
  TError,
  { id: string; data: UpdateClassLevelDto },
  TContext
> => {
  const mutationOptions = getClassLevelControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const classLevelControllerRemove = (id: string) => {
  return service<ActionResponseDto>({ url: `/class-level/${id}`, method: 'DELETE' });
};

export const getClassLevelControllerRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof classLevelControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof classLevelControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationKey = ['classLevelControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof classLevelControllerRemove>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return classLevelControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClassLevelControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof classLevelControllerRemove>>
>;

export type ClassLevelControllerRemoveMutationError = unknown;

export const useClassLevelControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof classLevelControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof classLevelControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationOptions = getClassLevelControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const classLevelControllerDeactivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/class-level/${id}/deactivate`, method: 'DELETE' });
};

export const getClassLevelControllerDeactivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof classLevelControllerDeactivate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof classLevelControllerDeactivate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['classLevelControllerDeactivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof classLevelControllerDeactivate>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return classLevelControllerDeactivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClassLevelControllerDeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof classLevelControllerDeactivate>>
>;

export type ClassLevelControllerDeactivateMutationError = unknown;

export const useClassLevelControllerDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof classLevelControllerDeactivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof classLevelControllerDeactivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getClassLevelControllerDeactivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const classLevelControllerActivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/class-level/${id}/activate`, method: 'PATCH' });
};

export const getClassLevelControllerActivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof classLevelControllerActivate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof classLevelControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationKey = ['classLevelControllerActivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof classLevelControllerActivate>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return classLevelControllerActivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClassLevelControllerActivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof classLevelControllerActivate>>
>;

export type ClassLevelControllerActivateMutationError = unknown;

export const useClassLevelControllerActivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof classLevelControllerActivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof classLevelControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getClassLevelControllerActivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
