export const styles = {
  wrapper: {
    position: 'relative',
    zIndex: 1,
    marginTop: 6,
    borderRadius: 2,
    backdropFilter: 'blur(24px)',
    WebkitBackdropFilter: 'blur(24px)',
    backgroundColor: 'secondary.light',
    width: 'calc(100% - 50px)',
    minHeight: '60vh',
  },
  container: {
    padding: 4,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    minHeight: '60vh',
    gap: 4,
    position: 'relative',
    width: '100%',
  },
  collapse: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  title: { textAlign: 'center', fontWeight: 400, fontSize: '3rem' },
  actions: {
    display: 'flex',
    gap: 2,
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 8,
    flexDirection: 'column',
    width: '100%',
  },
  actionButton: { minWidth: 280, mx: 2 },
  actionMessage: { color: 'primary.dark', fontSize: '1.5rem' },
} as const;
