export const styles = {
  wrapper: {
    position: 'relative',
    zIndex: 1,
    marginTop: 6,
    padding: 3,
    marginLeft: 4,
    marginRight: 4,
    paddingTop: 8,
    paddingBottom: 8,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: '#ddd',
  },
  title: { textAlign: 'center', fontWeight: 400, fontSize: '3rem' },
  description: { textAlign: 'center', fontWeight: 400, fontSize: '1.5rem' },
  branches: {
    display: 'flex',
    gap: 4,
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 8,
    flexDirection: 'row-reverse',
  },
  branch: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 6,
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 2,
    width: { xs: '90%', md: '30%' },
    // flex: 0.33,
  },
  branchTitle: { textAlign: 'center', fontWeight: 400, fontSize: '1.5rem', marginTop: 2 },
  branchDescription: { textAlign: 'center', fontWeight: 400, fontSize: '1rem' },
} as const;
