/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ActionResponseDto,
  AreaControllerFindAllParams,
  AreaControllerFindOneParams,
  CreateAreaDto,
  CreateAreaResponseDto,
  DetailAreasResponseDto,
  ListAreasResponseDto,
  UpdateAreaDto,
  UpdateAreaResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const areaControllerCreate = (createAreaDto: CreateAreaDto, signal?: AbortSignal) => {
  return service<CreateAreaResponseDto>({
    url: `/area`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createAreaDto,
    signal,
  });
};

export const getAreaControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof areaControllerCreate>>,
    TError,
    { data: CreateAreaDto },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof areaControllerCreate>>, TError, { data: CreateAreaDto }, TContext> => {
  const mutationKey = ['areaControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof areaControllerCreate>>, { data: CreateAreaDto }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return areaControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AreaControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof areaControllerCreate>>>;
export type AreaControllerCreateMutationBody = CreateAreaDto;
export type AreaControllerCreateMutationError = unknown;

export const useAreaControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof areaControllerCreate>>,
      TError,
      { data: CreateAreaDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof areaControllerCreate>>, TError, { data: CreateAreaDto }, TContext> => {
  const mutationOptions = getAreaControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const areaControllerFindAll = (params?: AreaControllerFindAllParams, signal?: AbortSignal) => {
  return service<ListAreasResponseDto>({ url: `/area`, method: 'GET', params, signal });
};

export const getAreaControllerFindAllQueryKey = (params?: AreaControllerFindAllParams) => {
  return [`/area`, ...(params ? [params] : [])] as const;
};

export const getAreaControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof areaControllerFindAll>>,
  TError = unknown,
>(
  params?: AreaControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof areaControllerFindAll>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAreaControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof areaControllerFindAll>>> = ({ signal }) =>
    areaControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof areaControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AreaControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof areaControllerFindAll>>>;
export type AreaControllerFindAllQueryError = unknown;

export function useAreaControllerFindAll<TData = Awaited<ReturnType<typeof areaControllerFindAll>>, TError = unknown>(
  params: undefined | AreaControllerFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof areaControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof areaControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof areaControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAreaControllerFindAll<TData = Awaited<ReturnType<typeof areaControllerFindAll>>, TError = unknown>(
  params?: AreaControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof areaControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof areaControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof areaControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAreaControllerFindAll<TData = Awaited<ReturnType<typeof areaControllerFindAll>>, TError = unknown>(
  params?: AreaControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof areaControllerFindAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAreaControllerFindAll<TData = Awaited<ReturnType<typeof areaControllerFindAll>>, TError = unknown>(
  params?: AreaControllerFindAllParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof areaControllerFindAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAreaControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const areaControllerFindOne = (id: string, params?: AreaControllerFindOneParams, signal?: AbortSignal) => {
  return service<DetailAreasResponseDto>({ url: `/area/${id}`, method: 'GET', params, signal });
};

export const getAreaControllerFindOneQueryKey = (id?: string, params?: AreaControllerFindOneParams) => {
  return [`/area/${id}`, ...(params ? [params] : [])] as const;
};

export const getAreaControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof areaControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: AreaControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof areaControllerFindOne>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAreaControllerFindOneQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof areaControllerFindOne>>> = ({ signal }) =>
    areaControllerFindOne(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof areaControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AreaControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof areaControllerFindOne>>>;
export type AreaControllerFindOneQueryError = unknown;

export function useAreaControllerFindOne<TData = Awaited<ReturnType<typeof areaControllerFindOne>>, TError = unknown>(
  id: string,
  params: undefined | AreaControllerFindOneParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof areaControllerFindOne>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof areaControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof areaControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAreaControllerFindOne<TData = Awaited<ReturnType<typeof areaControllerFindOne>>, TError = unknown>(
  id: string,
  params?: AreaControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof areaControllerFindOne>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof areaControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof areaControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAreaControllerFindOne<TData = Awaited<ReturnType<typeof areaControllerFindOne>>, TError = unknown>(
  id: string,
  params?: AreaControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof areaControllerFindOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAreaControllerFindOne<TData = Awaited<ReturnType<typeof areaControllerFindOne>>, TError = unknown>(
  id: string,
  params?: AreaControllerFindOneParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof areaControllerFindOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAreaControllerFindOneQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const areaControllerUpdate = (id: string, updateAreaDto: UpdateAreaDto) => {
  return service<UpdateAreaResponseDto>({
    url: `/area/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateAreaDto,
  });
};

export const getAreaControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof areaControllerUpdate>>,
    TError,
    { id: string; data: UpdateAreaDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof areaControllerUpdate>>,
  TError,
  { id: string; data: UpdateAreaDto },
  TContext
> => {
  const mutationKey = ['areaControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof areaControllerUpdate>>,
    { id: string; data: UpdateAreaDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return areaControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AreaControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof areaControllerUpdate>>>;
export type AreaControllerUpdateMutationBody = UpdateAreaDto;
export type AreaControllerUpdateMutationError = unknown;

export const useAreaControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof areaControllerUpdate>>,
      TError,
      { id: string; data: UpdateAreaDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof areaControllerUpdate>>,
  TError,
  { id: string; data: UpdateAreaDto },
  TContext
> => {
  const mutationOptions = getAreaControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const areaControllerRemove = (id: string) => {
  return service<ActionResponseDto>({ url: `/area/${id}`, method: 'DELETE' });
};

export const getAreaControllerRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof areaControllerRemove>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof areaControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationKey = ['areaControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof areaControllerRemove>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return areaControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AreaControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof areaControllerRemove>>>;

export type AreaControllerRemoveMutationError = unknown;

export const useAreaControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof areaControllerRemove>>, TError, { id: string }, TContext>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof areaControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationOptions = getAreaControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const areaControllerDeactivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/area/${id}/deactivate`, method: 'DELETE' });
};

export const getAreaControllerDeactivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof areaControllerDeactivate>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof areaControllerDeactivate>>, TError, { id: string }, TContext> => {
  const mutationKey = ['areaControllerDeactivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof areaControllerDeactivate>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return areaControllerDeactivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AreaControllerDeactivateMutationResult = NonNullable<Awaited<ReturnType<typeof areaControllerDeactivate>>>;

export type AreaControllerDeactivateMutationError = unknown;

export const useAreaControllerDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof areaControllerDeactivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof areaControllerDeactivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getAreaControllerDeactivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const areaControllerActivate = (id: string) => {
  return service<ActionResponseDto>({ url: `/area/${id}/activate`, method: 'PATCH' });
};

export const getAreaControllerActivateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof areaControllerActivate>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof areaControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationKey = ['areaControllerActivate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof areaControllerActivate>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return areaControllerActivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AreaControllerActivateMutationResult = NonNullable<Awaited<ReturnType<typeof areaControllerActivate>>>;

export type AreaControllerActivateMutationError = unknown;

export const useAreaControllerActivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof areaControllerActivate>>, TError, { id: string }, TContext>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof areaControllerActivate>>, TError, { id: string }, TContext> => {
  const mutationOptions = getAreaControllerActivateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
