/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ActionResponseDto,
  AdmissionsControllerFindAllParams,
  AdmissionsControllerFindOneParams,
  AdmissionsControllerSearchLegacyParams,
  CreateAdmissionDto,
  CreateAdmissionResponseDto,
  DetailAdmissionResponseDto,
  FinalizeAdmissionDto,
  FinalizeAdmissionResponseDto,
  ListAdmissionsResponseDto,
  MarkFeePaidDto,
  MarkFeePaidResponseDto,
  SearchLegacyAdmissionsResponseDto,
  UpdateAdmissionDto,
  UpdateAdmissionResponseDto,
  UpdateAdmissionStatusDto,
  UpdateAdmissionStatusResponseDto,
} from '../app.schemas';

import service from '../../../services/index';

export const admissionsControllerSearchLegacy = (
  params: AdmissionsControllerSearchLegacyParams,
  signal?: AbortSignal,
) => {
  return service<SearchLegacyAdmissionsResponseDto>({
    url: `/admissions/search/legacy`,
    method: 'GET',
    params,
    signal,
  });
};

export const getAdmissionsControllerSearchLegacyQueryKey = (params?: AdmissionsControllerSearchLegacyParams) => {
  return [`/admissions/search/legacy`, ...(params ? [params] : [])] as const;
};

export const getAdmissionsControllerSearchLegacyQueryOptions = <
  TData = Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>,
  TError = unknown,
>(
  params: AdmissionsControllerSearchLegacyParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdmissionsControllerSearchLegacyQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>> = ({ signal }) =>
    admissionsControllerSearchLegacy(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdmissionsControllerSearchLegacyQueryResult = NonNullable<
  Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>
>;
export type AdmissionsControllerSearchLegacyQueryError = unknown;

export function useAdmissionsControllerSearchLegacy<
  TData = Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>,
  TError = unknown,
>(
  params: AdmissionsControllerSearchLegacyParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>,
          TError,
          Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdmissionsControllerSearchLegacy<
  TData = Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>,
  TError = unknown,
>(
  params: AdmissionsControllerSearchLegacyParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>,
          TError,
          Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdmissionsControllerSearchLegacy<
  TData = Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>,
  TError = unknown,
>(
  params: AdmissionsControllerSearchLegacyParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAdmissionsControllerSearchLegacy<
  TData = Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>,
  TError = unknown,
>(
  params: AdmissionsControllerSearchLegacyParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerSearchLegacy>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdmissionsControllerSearchLegacyQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const admissionsControllerCreate = (createAdmissionDto: CreateAdmissionDto, signal?: AbortSignal) => {
  return service<CreateAdmissionResponseDto>({
    url: `/admissions`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createAdmissionDto,
    signal,
  });
};

export const getAdmissionsControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof admissionsControllerCreate>>,
    TError,
    { data: CreateAdmissionDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof admissionsControllerCreate>>,
  TError,
  { data: CreateAdmissionDto },
  TContext
> => {
  const mutationKey = ['admissionsControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof admissionsControllerCreate>>,
    { data: CreateAdmissionDto }
  > = (props) => {
    const { data } = props ?? {};

    return admissionsControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdmissionsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof admissionsControllerCreate>>
>;
export type AdmissionsControllerCreateMutationBody = CreateAdmissionDto;
export type AdmissionsControllerCreateMutationError = unknown;

export const useAdmissionsControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof admissionsControllerCreate>>,
      TError,
      { data: CreateAdmissionDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof admissionsControllerCreate>>,
  TError,
  { data: CreateAdmissionDto },
  TContext
> => {
  const mutationOptions = getAdmissionsControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const admissionsControllerFindAll = (params?: AdmissionsControllerFindAllParams, signal?: AbortSignal) => {
  return service<ListAdmissionsResponseDto>({ url: `/admissions`, method: 'GET', params, signal });
};

export const getAdmissionsControllerFindAllQueryKey = (params?: AdmissionsControllerFindAllParams) => {
  return [`/admissions`, ...(params ? [params] : [])] as const;
};

export const getAdmissionsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof admissionsControllerFindAll>>,
  TError = unknown,
>(
  params?: AdmissionsControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerFindAll>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdmissionsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof admissionsControllerFindAll>>> = ({ signal }) =>
    admissionsControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof admissionsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdmissionsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof admissionsControllerFindAll>>
>;
export type AdmissionsControllerFindAllQueryError = unknown;

export function useAdmissionsControllerFindAll<
  TData = Awaited<ReturnType<typeof admissionsControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | AdmissionsControllerFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof admissionsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof admissionsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdmissionsControllerFindAll<
  TData = Awaited<ReturnType<typeof admissionsControllerFindAll>>,
  TError = unknown,
>(
  params?: AdmissionsControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof admissionsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof admissionsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdmissionsControllerFindAll<
  TData = Awaited<ReturnType<typeof admissionsControllerFindAll>>,
  TError = unknown,
>(
  params?: AdmissionsControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAdmissionsControllerFindAll<
  TData = Awaited<ReturnType<typeof admissionsControllerFindAll>>,
  TError = unknown,
>(
  params?: AdmissionsControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerFindAll>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdmissionsControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const admissionsControllerFindOne = (
  id: string,
  params?: AdmissionsControllerFindOneParams,
  signal?: AbortSignal,
) => {
  return service<DetailAdmissionResponseDto>({ url: `/admissions/${id}`, method: 'GET', params, signal });
};

export const getAdmissionsControllerFindOneQueryKey = (id?: string, params?: AdmissionsControllerFindOneParams) => {
  return [`/admissions/${id}`, ...(params ? [params] : [])] as const;
};

export const getAdmissionsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof admissionsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: AdmissionsControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerFindOne>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdmissionsControllerFindOneQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof admissionsControllerFindOne>>> = ({ signal }) =>
    admissionsControllerFindOne(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof admissionsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdmissionsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof admissionsControllerFindOne>>
>;
export type AdmissionsControllerFindOneQueryError = unknown;

export function useAdmissionsControllerFindOne<
  TData = Awaited<ReturnType<typeof admissionsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params: undefined | AdmissionsControllerFindOneParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerFindOne>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof admissionsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof admissionsControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdmissionsControllerFindOne<
  TData = Awaited<ReturnType<typeof admissionsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: AdmissionsControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerFindOne>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof admissionsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof admissionsControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdmissionsControllerFindOne<
  TData = Awaited<ReturnType<typeof admissionsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: AdmissionsControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerFindOne>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAdmissionsControllerFindOne<
  TData = Awaited<ReturnType<typeof admissionsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: AdmissionsControllerFindOneParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof admissionsControllerFindOne>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdmissionsControllerFindOneQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const admissionsControllerUpdate = (id: string, updateAdmissionDto: UpdateAdmissionDto) => {
  return service<UpdateAdmissionResponseDto>({
    url: `/admissions/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateAdmissionDto,
  });
};

export const getAdmissionsControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof admissionsControllerUpdate>>,
    TError,
    { id: string; data: UpdateAdmissionDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof admissionsControllerUpdate>>,
  TError,
  { id: string; data: UpdateAdmissionDto },
  TContext
> => {
  const mutationKey = ['admissionsControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof admissionsControllerUpdate>>,
    { id: string; data: UpdateAdmissionDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return admissionsControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdmissionsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof admissionsControllerUpdate>>
>;
export type AdmissionsControllerUpdateMutationBody = UpdateAdmissionDto;
export type AdmissionsControllerUpdateMutationError = unknown;

export const useAdmissionsControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof admissionsControllerUpdate>>,
      TError,
      { id: string; data: UpdateAdmissionDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof admissionsControllerUpdate>>,
  TError,
  { id: string; data: UpdateAdmissionDto },
  TContext
> => {
  const mutationOptions = getAdmissionsControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const admissionsControllerRemove = (id: string) => {
  return service<ActionResponseDto>({ url: `/admissions/${id}`, method: 'DELETE' });
};

export const getAdmissionsControllerRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof admissionsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof admissionsControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationKey = ['admissionsControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof admissionsControllerRemove>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return admissionsControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdmissionsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof admissionsControllerRemove>>
>;

export type AdmissionsControllerRemoveMutationError = unknown;

export const useAdmissionsControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof admissionsControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof admissionsControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationOptions = getAdmissionsControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const admissionsControllerUpdateStatus = (id: string, updateAdmissionStatusDto: UpdateAdmissionStatusDto) => {
  return service<UpdateAdmissionStatusResponseDto>({
    url: `/admissions/${id}/status`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateAdmissionStatusDto,
  });
};

export const getAdmissionsControllerUpdateStatusMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof admissionsControllerUpdateStatus>>,
    TError,
    { id: string; data: UpdateAdmissionStatusDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof admissionsControllerUpdateStatus>>,
  TError,
  { id: string; data: UpdateAdmissionStatusDto },
  TContext
> => {
  const mutationKey = ['admissionsControllerUpdateStatus'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof admissionsControllerUpdateStatus>>,
    { id: string; data: UpdateAdmissionStatusDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return admissionsControllerUpdateStatus(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdmissionsControllerUpdateStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof admissionsControllerUpdateStatus>>
>;
export type AdmissionsControllerUpdateStatusMutationBody = UpdateAdmissionStatusDto;
export type AdmissionsControllerUpdateStatusMutationError = unknown;

export const useAdmissionsControllerUpdateStatus = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof admissionsControllerUpdateStatus>>,
      TError,
      { id: string; data: UpdateAdmissionStatusDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof admissionsControllerUpdateStatus>>,
  TError,
  { id: string; data: UpdateAdmissionStatusDto },
  TContext
> => {
  const mutationOptions = getAdmissionsControllerUpdateStatusMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const admissionsControllerMarkFeePaid = (id: string, markFeePaidDto: MarkFeePaidDto) => {
  return service<MarkFeePaidResponseDto>({
    url: `/admissions/${id}/fee-paid`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: markFeePaidDto,
  });
};

export const getAdmissionsControllerMarkFeePaidMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof admissionsControllerMarkFeePaid>>,
    TError,
    { id: string; data: MarkFeePaidDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof admissionsControllerMarkFeePaid>>,
  TError,
  { id: string; data: MarkFeePaidDto },
  TContext
> => {
  const mutationKey = ['admissionsControllerMarkFeePaid'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof admissionsControllerMarkFeePaid>>,
    { id: string; data: MarkFeePaidDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return admissionsControllerMarkFeePaid(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdmissionsControllerMarkFeePaidMutationResult = NonNullable<
  Awaited<ReturnType<typeof admissionsControllerMarkFeePaid>>
>;
export type AdmissionsControllerMarkFeePaidMutationBody = MarkFeePaidDto;
export type AdmissionsControllerMarkFeePaidMutationError = unknown;

export const useAdmissionsControllerMarkFeePaid = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof admissionsControllerMarkFeePaid>>,
      TError,
      { id: string; data: MarkFeePaidDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof admissionsControllerMarkFeePaid>>,
  TError,
  { id: string; data: MarkFeePaidDto },
  TContext
> => {
  const mutationOptions = getAdmissionsControllerMarkFeePaidMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const admissionsControllerFinalize = (id: string, finalizeAdmissionDto: FinalizeAdmissionDto) => {
  return service<FinalizeAdmissionResponseDto>({
    url: `/admissions/${id}/finalize`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: finalizeAdmissionDto,
  });
};

export const getAdmissionsControllerFinalizeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof admissionsControllerFinalize>>,
    TError,
    { id: string; data: FinalizeAdmissionDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof admissionsControllerFinalize>>,
  TError,
  { id: string; data: FinalizeAdmissionDto },
  TContext
> => {
  const mutationKey = ['admissionsControllerFinalize'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof admissionsControllerFinalize>>,
    { id: string; data: FinalizeAdmissionDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return admissionsControllerFinalize(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdmissionsControllerFinalizeMutationResult = NonNullable<
  Awaited<ReturnType<typeof admissionsControllerFinalize>>
>;
export type AdmissionsControllerFinalizeMutationBody = FinalizeAdmissionDto;
export type AdmissionsControllerFinalizeMutationError = unknown;

export const useAdmissionsControllerFinalize = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof admissionsControllerFinalize>>,
      TError,
      { id: string; data: FinalizeAdmissionDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof admissionsControllerFinalize>>,
  TError,
  { id: string; data: FinalizeAdmissionDto },
  TContext
> => {
  const mutationOptions = getAdmissionsControllerFinalizeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
