/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dr-core-service
 * OpenAPI spec version: 1.0.0
 */
export interface AdminLoginRequestDto {
  /** Admin email address */
  email: string;
  /**
   * Admin password
   * @minLength 6
   */
  password: string;
  /** Captcha token (required when CAPTCHA_BYPASS is not enabled) */
  captchaToken?: string;
}

export interface AdminLoginResponseDto {
  /** JWT access token */
  accessToken: string;
  /** JWT refresh token */
  refreshToken: string;
  /** Token expiration time */
  expiresIn: number;
  /** Whether the user needs to change their temporary password */
  requiresPasswordChange: boolean;
}

export interface AdminLoginFirebaseRequestDto {
  /** Firebase ID token */
  idToken: string;
}

export interface AdminRefreshRequestDto {
  /** JWT refresh token */
  refreshToken: string;
}

export interface AdminRefreshResponseDto {
  /** JWT access token */
  accessToken: string;
  /** JWT refresh token */
  refreshToken: string;
  /** Token expiration time */
  expiresIn: number;
  /** Whether the user needs to change their temporary password */
  requiresPasswordChange: boolean;
}

export interface AdminUser {
  /** The ID of the admin user */
  id: string;
  /** The name of the admin user */
  name: string;
  /** The email of the admin user */
  email: string;
  /** The role of the admin user */
  role: string;
  /** Whether the admin user is active */
  isActive: boolean;
  /** Whether the admin user is forced to change their password */
  forcePasswordChange: boolean;
  /** Count of consecutive failed login attempts */
  failedLoginAttempts: number;
  /** Whether login is disabled due to failed attempts */
  isLoginDisabled: boolean;
  /** When the admin user was created */
  createdAt: string;
  /** When the admin user was last updated */
  updatedAt?: string;
  /** The temporary password of the admin user, used for initial login */
  tempPassword?: string;
}

export interface AdminDetailResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface AdminEnableLoginRequestDto {
  /** Admin user id to re-enable login for */
  adminUserId: string;
}

export interface AdminEnableLoginResponseDto {
  /** Message of the action */
  message: string;
}

export interface CreateAdminUserDto {
  /** Admin name */
  name: string;
  /** Admin email address */
  email: string;
}

export interface CreateAdminUserResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface ListAdminUsersResponseDto {
  /** Total number of records */
  count: number;
  data: AdminUser[];
}

export interface DetailAdminUserResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface UpdateAdminUserDto {
  /** Admin name */
  name?: string;
  /** Admin email address */
  email?: string;
}

export interface UpdateAdminUserResponseDto {
  /** Admin user data */
  data: AdminUser;
}

export interface ActionResponseDto {
  /** Message of the action */
  message: string;
}

export interface AdminChangePasswordRequestDto {
  /** Current password */
  currentPassword: string;
  /** New password */
  newPassword: string;
}

export interface AdminChangePasswordResponseDto {
  /** Success message */
  message: string;
}

export interface AdminForgotPasswordRequestDto {
  /** Admin email address */
  email: string;
  /** Captcha token (required when CAPTCHA_BYPASS is not enabled) */
  captchaToken?: string;
}

export interface AdminForgotPasswordResponseDto {
  /** Success message */
  message: string;
  /** Reset token */
  token: string;
}

export interface AdminResetPasswordRequestDto {
  /** Reset token received via email */
  token: string;
  /** New password */
  newPassword: string;
  /** Captcha token (required when CAPTCHA_BYPASS is not enabled) */
  captchaToken?: string;
}

export interface AdminResetPasswordResponseDto {
  /** Success message */
  message: string;
}

export interface AdminCreatePasswordRequestDto {
  /** New password to replace temporary password */
  newPassword: string;
}

export interface AdminCreatePasswordResponseDto {
  /** Success message */
  message: string;
}

export interface CreateBranchDto {
  /** code */
  code: string;
  /** name */
  name: string;
}

export interface AdminUserBase {
  /** The ID of the admin user */
  id: string;
  /** The name of the admin user */
  name: string;
  /** The email of the admin user */
  email: string;
}

export interface Branch {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateBranchResponseDto {
  /** Message of the action */
  message: string;
  data: Branch;
}

export interface ListBranchesResponseDto {
  /** Total number of records */
  count: number;
  data: Branch[];
}

export interface DetailBranchesResponseDto {
  /** Message of the action */
  message: string;
  data: Branch;
}

export interface UpdateBranchDto {
  /** code */
  code?: string;
  /** name */
  name?: string;
}

export interface UpdateBranchResponseDto {
  /** Message of the action */
  message: string;
  data?: Branch;
}

export interface CreateAreaDto {
  /** branchId */
  branchId: string;
  /** alias */
  alias: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** hasVan */
  hasVan?: boolean;
  /** hasBoysVan */
  hasBoysVan?: boolean;
}

export interface AreaBranch {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
}

export interface Area {
  /** id */
  id: string;
  /** branch */
  branch: AreaBranch;
  /** alias */
  alias: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** hasVan */
  hasVan: boolean;
  /** hasBoysVan */
  hasBoysVan: boolean;
  /** lastYearTotal */
  lastYearTotal: number;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateAreaResponseDto {
  /** Message of the action */
  message: string;
  data: Area;
}

export interface ListAreasResponseDto {
  /** Total number of records */
  count: number;
  data: Area[];
}

export interface DetailAreasResponseDto {
  /** Message of the action */
  message: string;
  data: Area;
}

export interface UpdateAreaDto {
  /** branchId */
  branchId?: string;
  /** alias */
  alias?: string;
  /** code */
  code?: string;
  /** name */
  name?: string;
  /** hasVan */
  hasVan?: boolean;
  /** hasBoysVan */
  hasBoysVan?: boolean;
}

export interface UpdateAreaResponseDto {
  /** Message of the action */
  message: string;
  data?: Area;
}

export interface CreateSessionDto {
  /** name */
  name: string;
  /** attendanceDays */
  attendanceDays?: number;
  /** startsAt */
  startsAt?: string;
  /** endsAt */
  endsAt?: string;
}

export interface Session {
  /** id */
  id: string;
  /** name */
  name: string;
  /** attendanceDays */
  attendanceDays: number;
  /** startsAt */
  startsAt?: string;
  /** endsAt */
  endsAt?: string;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateSessionResponseDto {
  /** Message of the action */
  message: string;
  data: Session;
}

export interface ListSessionsResponseDto {
  /** Total number of records */
  count: number;
  data: Session[];
}

export interface DetailSessionsResponseDto {
  /** Message of the action */
  message: string;
  data: Session;
}

export interface UpdateSessionDto {
  /** name */
  name?: string;
  /** attendanceDays */
  attendanceDays?: number;
  /** startsAt */
  startsAt?: string;
  /** endsAt */
  endsAt?: string;
}

export interface UpdateSessionResponseDto {
  /** Message of the action */
  message: string;
  data?: Session;
}

export interface AttendanceDay {
  /** id */
  id: string;
  /** sessionId */
  sessionId: string;
  /** date */
  date: string;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface ListAttendanceDaysResponseDto {
  /** Total number of records */
  count: number;
  data: AttendanceDay[];
}

export type BulkAttendanceRecordItemDtoStatus =
  (typeof BulkAttendanceRecordItemDtoStatus)[keyof typeof BulkAttendanceRecordItemDtoStatus];

export const BulkAttendanceRecordItemDtoStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED',
} as const;

export interface BulkAttendanceRecordItemDto {
  /** admissionId */
  admissionId: string;
  status: BulkAttendanceRecordItemDtoStatus;
}

export interface BulkUpsertAttendanceRecordsDto {
  records: BulkAttendanceRecordItemDto[];
}

export interface BulkUpsertAttendanceRecordsResponseDto {
  /** Message of the action */
  message: string;
}

export type AttendanceSummaryRowStatus = (typeof AttendanceSummaryRowStatus)[keyof typeof AttendanceSummaryRowStatus];

export const AttendanceSummaryRowStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED',
} as const;

export interface AttendanceSummaryRow {
  /** classLevelId */
  classLevelId: string;
  status: AttendanceSummaryRowStatus;
  /** count */
  count: number;
}

export interface AttendanceSummaryResponseDto {
  /** Message of the action */
  message: string;
  data: AttendanceSummaryRow[];
}

export type StudentAttendanceHistoryRowStatus =
  (typeof StudentAttendanceHistoryRowStatus)[keyof typeof StudentAttendanceHistoryRowStatus];

export const StudentAttendanceHistoryRowStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED',
} as const;

export interface StudentAttendanceHistoryRow {
  /** attendanceDayId */
  attendanceDayId: string;
  /** date */
  date: string;
  status: StudentAttendanceHistoryRowStatus;
}

export interface StudentAttendanceHistoryResponseDto {
  /** Message of the action */
  message: string;
  data: StudentAttendanceHistoryRow[];
}

/**
 * gender
 */
export type CreateClassLevelDtoGender = (typeof CreateClassLevelDtoGender)[keyof typeof CreateClassLevelDtoGender];

export const CreateClassLevelDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface CreateClassLevelDto {
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: CreateClassLevelDtoGender;
  /** sortOrder */
  sortOrder?: number;
}

/**
 * gender
 */
export type ClassLevelGender = (typeof ClassLevelGender)[keyof typeof ClassLevelGender];

export const ClassLevelGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface ClassLevel {
  /** id */
  id: string;
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: ClassLevelGender;
  /** sortOrder */
  sortOrder: number;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
  /** createdBy */
  createdBy?: AdminUserBase;
  /** updatedBy */
  updatedBy?: AdminUserBase;
}

export interface CreateClassLevelResponseDto {
  /** Message of the action */
  message: string;
  data: ClassLevel;
}

export interface ListClassLevelsResponseDto {
  /** Total number of records */
  count: number;
  data: ClassLevel[];
}

export interface DetailClassLevelsResponseDto {
  /** Message of the action */
  message: string;
  data: ClassLevel;
}

/**
 * gender
 */
export type UpdateClassLevelDtoGender = (typeof UpdateClassLevelDtoGender)[keyof typeof UpdateClassLevelDtoGender];

export const UpdateClassLevelDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface UpdateClassLevelDto {
  /** age */
  age?: number;
  /** code */
  code?: string;
  /** name */
  name?: string;
  /** gender */
  gender?: UpdateClassLevelDtoGender;
  /** sortOrder */
  sortOrder?: number;
}

export interface UpdateClassLevelResponseDto {
  /** Message of the action */
  message: string;
  data?: ClassLevel;
}

export interface LegacyStudentRow {
  /** id */
  id: string;
  /** grNumber (legacy gr_no) */
  grNumber?: string;
  /** name */
  name?: string;
  /** fatherName (legacy fathers_name) */
  fatherName?: string;
  /** dateOfBirth */
  dateOfBirth?: string;
  /** gender (legacy free-form text) */
  gender?: string;
  /** phone */
  phone?: string;
  /** identityNumber (legacy b_form_or_birth_certificate_no) */
  identityNumber?: string;
  /** isVerified */
  isVerified?: boolean;
}

export interface SearchLegacyAdmissionsResponseDto {
  /** Total number of records */
  count: number;
  data: LegacyStudentRow[];
}

export type CreateAdmissionDtoGender = (typeof CreateAdmissionDtoGender)[keyof typeof CreateAdmissionDtoGender];

export const CreateAdmissionDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface CreateAdmissionDto {
  /** sessionId */
  sessionId: string;
  /** legacyStudentId (optional for legacy prefill) */
  legacyStudentId?: string;
  /** branchId */
  branchId: string;
  /** areaId */
  areaId: string;
  /** student name */
  name: string;
  /** father/guardian name */
  fatherName: string;
  /** dateOfBirth */
  dateOfBirth: string;
  gender: CreateAdmissionDtoGender;
  /** phone */
  phone: string;
  /** alternatePhone */
  alternatePhone?: string;
  /** address */
  address?: string;
  /** identityNumber (B-Form/CNIC as text) */
  identityNumber?: string;
  /** schoolName */
  schoolName?: string;
  /** lastYearClass */
  lastYearClass?: string;
  /** vanRequired */
  vanRequired?: boolean;
  /** isMarried */
  isMarried?: boolean;
  /** isWorking */
  isWorking?: boolean;
  /** identityProofAssetId */
  identityProofAssetId?: string;
  /** photoAssetId */
  photoAssetId?: string;
}

export interface AdmissionSession {
  /** id */
  id: string;
  /** name */
  name: string;
}

export type AdmissionStudentGender = (typeof AdmissionStudentGender)[keyof typeof AdmissionStudentGender];

export const AdmissionStudentGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AdmissionStudent {
  /** id */
  id: string;
  /** grNumber */
  grNumber: string;
  /** name */
  name: string;
  /** fatherName */
  fatherName: string;
  /** dateOfBirth */
  dateOfBirth: string;
  gender: AdmissionStudentGender;
  /** phone */
  phone: string;
  /** alternatePhone */
  alternatePhone?: string;
  /** address */
  address?: string;
  /** identityNumber */
  identityNumber?: string;
  /** identityProofAssetId */
  identityProofAssetId?: string;
  /** photoAssetId */
  photoAssetId?: string;
}

export interface AdmissionBranch {
  /** id */
  id: string;
  /** code */
  code: string;
  /** name */
  name: string;
}

export interface AdmissionArea {
  /** id */
  id: string;
  /** alias */
  alias: string;
  /** code */
  code: string;
  /** name */
  name: string;
  /** hasVan */
  hasVan: boolean;
  /** hasBoysVan */
  hasBoysVan: boolean;
}

/**
 * gender
 */
export type AdmissionClassLevelGender = (typeof AdmissionClassLevelGender)[keyof typeof AdmissionClassLevelGender];

export const AdmissionClassLevelGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface AdmissionClassLevel {
  /** id */
  id: string;
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: AdmissionClassLevelGender;
}

export type AdmissionStatus = (typeof AdmissionStatus)[keyof typeof AdmissionStatus];

export const AdmissionStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export interface Admission {
  /** id */
  id: string;
  status: AdmissionStatus;
  /** rejectedReason */
  rejectedReason?: string;
  /** session */
  session: AdmissionSession;
  /** student */
  student: AdmissionStudent;
  /** branch */
  branch: AdmissionBranch;
  /** area */
  area: AdmissionArea;
  /** classLevel */
  classLevel: AdmissionClassLevel;
  /** schoolName */
  schoolName?: string;
  /** lastYearClass */
  lastYearClass?: string;
  /** vanRequired */
  vanRequired: boolean;
  /** isMarried */
  isMarried: boolean;
  /** isWorking */
  isWorking: boolean;
  /** isFinalized */
  isFinalized: boolean;
  /** finalizedAt */
  finalizedAt?: string;
  /** finalizedByAdmin */
  finalizedByAdmin?: AdminUserBase;
  /** isFeePaid */
  isFeePaid: boolean;
  /** feePaidAt */
  feePaidAt?: string;
  /** feePaidByAdmin */
  feePaidByAdmin?: AdminUserBase;
  /** legacyStudentId */
  legacyStudentId?: string;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface CreateAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export interface ListAdmissionsResponseDto {
  /** Total number of records */
  count: number;
  data: Admission[];
}

export interface DetailAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export type UpdateAdmissionDtoGender = (typeof UpdateAdmissionDtoGender)[keyof typeof UpdateAdmissionDtoGender];

export const UpdateAdmissionDtoGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface UpdateAdmissionDto {
  /** branchId */
  branchId?: string;
  /** areaId */
  areaId?: string;
  /** student name */
  name?: string;
  /** father/guardian name */
  fatherName?: string;
  /** dateOfBirth */
  dateOfBirth?: string;
  gender?: UpdateAdmissionDtoGender;
  /** phone */
  phone?: string;
  /** alternatePhone */
  alternatePhone?: string;
  /** address */
  address?: string;
  /** identityNumber */
  identityNumber?: string;
  /** schoolName */
  schoolName?: string;
  /** lastYearClass */
  lastYearClass?: string;
  /** vanRequired */
  vanRequired?: boolean;
  /** isMarried */
  isMarried?: boolean;
  /** isWorking */
  isWorking?: boolean;
  /** identityProofAssetId */
  identityProofAssetId?: string;
  /** photoAssetId */
  photoAssetId?: string;
}

export interface UpdateAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data?: Admission;
}

export type UpdateAdmissionStatusDtoStatus =
  (typeof UpdateAdmissionStatusDtoStatus)[keyof typeof UpdateAdmissionStatusDtoStatus];

export const UpdateAdmissionStatusDtoStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export interface UpdateAdmissionStatusDto {
  status: UpdateAdmissionStatusDtoStatus;
  /** rejectedReason (required when status=REJECTED) */
  rejectedReason?: string;
  /** adminUserId (optional, for audit fields) */
  adminUserId?: string;
}

export interface UpdateAdmissionStatusResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export interface MarkFeePaidDto {
  /** isFeePaid */
  isFeePaid: boolean;
  /** adminUserId (optional, for audit fields) */
  adminUserId?: string;
}

export interface MarkFeePaidResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export interface FinalizeAdmissionDto {
  /** isFinalized */
  isFinalized: boolean;
  /** adminUserId (optional, for audit fields) */
  adminUserId?: string;
}

export interface FinalizeAdmissionResponseDto {
  /** Message of the action */
  message: string;
  data: Admission;
}

export interface InteractionTemplateStudent {
  id: string;
  grNumber: string;
  name: string;
  fatherName: string;
}

export interface InteractionTemplateAdmission {
  id: string;
  sessionId: string;
  classLevelId: string;
}

export interface InteractionTemplateQuestionSet {
  id: string;
  title: string;
}

export interface InteractionQuestion {
  /** Question id */
  id: string;
  /** Prompt to display to teacher */
  prompt: string;
  /** Sort order */
  sortOrder: number;
}

export interface InteractionTemplate {
  student: InteractionTemplateStudent;
  admission: InteractionTemplateAdmission;
  questionSet: InteractionTemplateQuestionSet;
  questions: InteractionQuestion[];
}

export interface GetInteractionTemplateResponseDto {
  /** Message of the action */
  message: string;
  data: InteractionTemplate;
}

export interface CreateInteractionRatingDto {
  /** Question id */
  questionId: string;
  /**
   * Rating value (1..5)
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /** Optional notes for this question */
  notes?: string;
}

export interface CreateInteractionDto {
  /** Student id (from search / QR) */
  studentId: string;
  /** Overall notes for interaction */
  notes?: string;
  ratings: CreateInteractionRatingDto[];
}

export interface CreateInteractionResponseData {
  id: string;
  admissionId: string;
}

export interface CreateInteractionResponseDto {
  /** Message of the action */
  message: string;
  data: CreateInteractionResponseData;
}

export interface CreateQuestionSetQuestionDto {
  /** prompt */
  prompt: string;
  /** sortOrder (defaults to array index) */
  sortOrder?: number;
}

export interface CreateQuestionSetDto {
  /** sessionId */
  sessionId: string;
  /** classLevelId */
  classLevelId: string;
  /** title */
  title: string;
  /** questions */
  questions: CreateQuestionSetQuestionDto[];
}

export interface QuestionSetSession {
  /** id */
  id: string;
  /** name */
  name: string;
}

/**
 * gender
 */
export type QuestionSetClassLevelGender =
  (typeof QuestionSetClassLevelGender)[keyof typeof QuestionSetClassLevelGender];

export const QuestionSetClassLevelGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export interface QuestionSetClassLevel {
  /** id */
  id: string;
  /** age */
  age: number;
  /** code */
  code: string;
  /** name */
  name: string;
  /** gender */
  gender: QuestionSetClassLevelGender;
}

export interface QuestionSetQuestion {
  /** id */
  id: string;
  /** prompt */
  prompt: string;
  /** sortOrder */
  sortOrder: number;
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface QuestionSet {
  /** id */
  id: string;
  /** session */
  session: QuestionSetSession;
  /** classLevel */
  classLevel: QuestionSetClassLevel;
  /** title */
  title: string;
  /** questions */
  questions: QuestionSetQuestion[];
  /** isActive */
  isActive: boolean;
  /** createdAt */
  createdAt: string;
  /** updatedAt */
  updatedAt?: string;
}

export interface CreateQuestionSetResponseDto {
  /** Message of the action */
  message: string;
  data: QuestionSet;
}

export interface ListQuestionSetsResponseDto {
  /** Total number of records */
  count: number;
  data: QuestionSet[];
}

export interface DetailQuestionSetsResponseDto {
  /** Message of the action */
  message: string;
  data: QuestionSet;
}

export interface UpdateQuestionSetDto {
  /** sessionId */
  sessionId?: string;
  /** classLevelId */
  classLevelId?: string;
  /** title */
  title?: string;
  /** Replace all questions when provided (full replacement) */
  questions?: CreateQuestionSetQuestionDto[];
}

export interface UpdateQuestionSetResponseDto {
  /** Message of the action */
  message: string;
  data?: QuestionSet;
}

export interface ImportLegacyStudentsRequestDto {
  /** CSV file to import */
  file: Blob;
}

export interface ImportLegacyStudentsResponseDto {
  /** Message of the action */
  message: string;
  /** Total records processed */
  totalProcessed: number;
  /** Records successfully imported */
  successCount: number;
  /** Records skipped (duplicates) */
  skippedCount: number;
  /** Records that failed to import */
  errorCount: number;
  /** Error details */
  errors?: string[];
}

export interface LegacyStudent {
  /** Unique identifier */
  id: string;
  /** Student name */
  name?: string;
  /** Father's name */
  fathersName?: string;
  /** Date of birth */
  dateOfBirth?: string;
  /** Address */
  address?: string;
  /** Area */
  area?: string;
  /** City */
  city?: string;
  /** Is school going */
  isSchoolGoing?: string;
  /** School name */
  schoolName?: string;
  /** School class */
  schoolClass?: string;
  /** Previously attended madressa */
  previouslyAttendedMadressa?: string;
  /** Previously attended year */
  previouslyAttendedYear?: string;
  /** Previously attended class */
  previouslyAttendedClass?: string;
  /** Phone number */
  phoneNumber?: string;
  /** WhatsApp number */
  whatsappNumber?: string;
  /** Gender */
  gender?: string;
  /** Is married */
  isMarried?: string;
  /** Is working */
  isWorking?: string;
  /** Work type */
  workType?: string;
  /** Email address */
  emailAddress?: string;
  /** Is van required */
  isVanRequired?: string;
  /** Is verified */
  isVerified?: boolean;
  /** Card printed */
  cardPrinted?: boolean;
  /** Van stop */
  vanStop?: string;
  /** B-Form or birth certificate number */
  bFormOrBirthCertificateNo?: string;
  /** GR number */
  grNo?: string;
  /** Category */
  category?: string;
  /** Image URL */
  imageUrl?: string;
  /** Is fees paid */
  isFeesPaid?: string;
  /** Updated by */
  updatedBy?: string;
  /** Admission year */
  admissionYear?: string;
  /** Created at */
  createdAt: string;
  /** Updated at */
  updatedAt?: string;
}

export interface ListLegacyStudentsResponseDto {
  /** Total count */
  count: number;
  /** List of legacy students */
  data: LegacyStudent[];
}

export interface ClearLegacyStudentsRequestDto {
  /** Confirm deletion */
  confirm: boolean;
}

export interface ClearLegacyStudentsResponseDto {
  /** Message of the action */
  message: string;
  /** Number of records deleted */
  deletedCount: number;
}

export type BranchControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: BranchControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * code
   */
  code?: string;
  /**
   * name
   */
  name?: string;
  /**
   * Sort by
   */
  sortBy?: BranchControllerFindAllSortBy;
};

export type BranchControllerFindAllSortOrder =
  (typeof BranchControllerFindAllSortOrder)[keyof typeof BranchControllerFindAllSortOrder];

export const BranchControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type BranchControllerFindAllSortBy =
  (typeof BranchControllerFindAllSortBy)[keyof typeof BranchControllerFindAllSortBy];

export const BranchControllerFindAllSortBy = {
  id: 'id',
  code: 'code',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type BranchControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type AreaControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AreaControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * branchId
   */
  branchId?: string;
  /**
   * alias
   */
  alias?: string;
  /**
   * code
   */
  code?: string;
  /**
   * name
   */
  name?: string;
  /**
   * hasVan
   */
  hasVan?: boolean;
  /**
   * hasBoysVan
   */
  hasBoysVan?: boolean;
  /**
   * Sort by
   */
  sortBy?: AreaControllerFindAllSortBy;
};

export type AreaControllerFindAllSortOrder =
  (typeof AreaControllerFindAllSortOrder)[keyof typeof AreaControllerFindAllSortOrder];

export const AreaControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AreaControllerFindAllSortBy =
  (typeof AreaControllerFindAllSortBy)[keyof typeof AreaControllerFindAllSortBy];

export const AreaControllerFindAllSortBy = {
  id: 'id',
  branchId: 'branchId',
  code: 'code',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type AreaControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type ClassLevelControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: ClassLevelControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * age
   */
  age?: number;
  /**
   * code
   */
  code?: string;
  /**
   * name
   */
  name?: string;
  /**
   * gender
   */
  gender?: ClassLevelControllerFindAllGender;
  /**
   * Sort by
   */
  sortBy?: ClassLevelControllerFindAllSortBy;
};

export type ClassLevelControllerFindAllSortOrder =
  (typeof ClassLevelControllerFindAllSortOrder)[keyof typeof ClassLevelControllerFindAllSortOrder];

export const ClassLevelControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ClassLevelControllerFindAllGender =
  (typeof ClassLevelControllerFindAllGender)[keyof typeof ClassLevelControllerFindAllGender];

export const ClassLevelControllerFindAllGender = {
  FEMALE: 'FEMALE',
  MALE: 'MALE',
} as const;

export type ClassLevelControllerFindAllSortBy =
  (typeof ClassLevelControllerFindAllSortBy)[keyof typeof ClassLevelControllerFindAllSortBy];

export const ClassLevelControllerFindAllSortBy = {
  id: 'id',
  age: 'age',
  code: 'code',
  name: 'name',
  gender: 'gender',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type ClassLevelControllerFindOneParams = {
  /**
   * Include deactivated records (admins only)
   */
  includeInActive?: boolean;
};

export type AdmissionsControllerSearchLegacyParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AdmissionsControllerSearchLegacySortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * Search query (GR, phone, name, father name)
   */
  query: string;
  /**
   * Sort by
   */
  sortBy?: AdmissionsControllerSearchLegacySortBy;
};

export type AdmissionsControllerSearchLegacySortOrder =
  (typeof AdmissionsControllerSearchLegacySortOrder)[keyof typeof AdmissionsControllerSearchLegacySortOrder];

export const AdmissionsControllerSearchLegacySortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AdmissionsControllerSearchLegacySortBy =
  (typeof AdmissionsControllerSearchLegacySortBy)[keyof typeof AdmissionsControllerSearchLegacySortBy];

export const AdmissionsControllerSearchLegacySortBy = {
  grNo: 'grNo',
  name: 'name',
  fathersName: 'fathersName',
  phoneNumber: 'phoneNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type AdmissionsControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Sort direction
   */
  sortOrder?: AdmissionsControllerFindAllSortOrder;
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
  /**
   * sessionId
   */
  sessionId?: string;
  /**
   * grNumber (exact match)
   */
  grNumber?: string;
  /**
   * name (contains)
   */
  name?: string;
  /**
   * fatherName (contains)
   */
  fatherName?: string;
  /**
   * phone (contains)
   */
  phone?: string;
  /**
   * schoolName (contains)
   */
  schoolName?: string;
  /**
   * classLevelId
   */
  classLevelId?: string;
  status?: AdmissionsControllerFindAllStatus;
  /**
   * isFeePaid
   */
  isFeePaid?: boolean;
  /**
   * Sort by
   */
  sortBy?: AdmissionsControllerFindAllSortBy;
};

export type AdmissionsControllerFindAllSortOrder =
  (typeof AdmissionsControllerFindAllSortOrder)[keyof typeof AdmissionsControllerFindAllSortOrder];

export const AdmissionsControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type AdmissionsControllerFindAllStatus =
  (typeof AdmissionsControllerFindAllStatus)[keyof typeof AdmissionsControllerFindAllStatus];

export const AdmissionsControllerFindAllStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
} as const;

export type AdmissionsControllerFindAllSortBy =
  (typeof AdmissionsControllerFindAllSortBy)[keyof typeof AdmissionsControllerFindAllSortBy];

export const AdmissionsControllerFindAllSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  status: 'status',
  isFeePaid: 'isFeePaid',
} as const;

export type AdmissionsControllerFindOneParams = {
  /**
   * Include deactivated records
   */
  includeInActive?: boolean;
};
